# Generated by Django 5.2.4 on 2025-10-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_qrcodedata_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='password_protected',
            field=models.BooleanField(default=False),
        ),
    ]
