# Generated by Django 5.2.4 on 2025-10-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_qrcodedata_hint_qrcodedata_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodedata',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='password_protected',
        ),
    ]
